<a href="https://colab.research.google.com/github/KISHOREKANCHI/TASK1-IRIS-FLOWER-CLASSIFICATION/blob/main/IRIS_FLOWER_CLASIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import plotly
import plotly.express as px
import cufflinks as cf
import plotly.offline as pyo
import matplotlib.pyplot as plt
from plotly.offline import init_notebook_mode,plot,iplot
from google.colab import drive
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
%matplotlib inline


In [ ]:
drive.mount('/content/gdrive')
iris=pd.read_csv('/content/gdrive/MyDrive/Iris.csv')


Mounted at /content/gdrive


In [ ]:
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
iris.drop("Id",axis=1,inplace=True)
iris

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
#vizualization

In [ ]:
px.scatter(iris,x="Species",y="PetalWidthCm",size="PetalWidthCm")

In [ ]:
px.bar(iris,x="Species",y="PetalWidthCm")

In [ ]:
px.line(iris,x="Species",y="PetalWidthCm")

In [ ]:
px.scatter_matrix(iris,color='Species',title='Iris',dimensions=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])

In [ ]:
#Data Processing

In [ ]:
x=iris.drop("Species",axis=1)
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
y=iris.Species
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
x=np.array(x)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)

In [ ]:
xtest

array([[5.5, 2.4, 3.7, 1. ],
       [5.4, 3.4, 1.7, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [6.7, 3.3, 5.7, 2.5],
       [5.4, 3. , 4.5, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.8, 2.6, 4. , 1.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [4.8, 3.1, 1.6, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [4.4, 3.2, 1.3, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 2.5, 3. , 1.1],
       [7.7, 3. , 6.1, 2.3],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [4.3, 3. , 1.1, 0.1],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 2.7, 5.3, 1.9],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 3.8, 1.7, 0.3],
       [6.3, 2.7, 4.9, 1.8],
       [5.5, 2.4, 3.8, 1.1],
       [6.6, 2.9, 4.6, 1.3],
       [7.2, 3.6, 6.1, 2.5],
       [4.6, 3.1, 1.5, 0.2],
       [6.7, 3

In [ ]:
lr=LogisticRegression()
lr.fit(xtrain,ytrain)

LogisticRegression()

In [ ]:
prediction=lr.predict(xtest)
prediction = [1 if x >= 0.5 else 0 for x in prediction]
accuracy=accuracy_score(ytest,prediction)*100

In [ ]:
accuracy

66.66666666666666

In [ ]:
print(ytest)
print(np.array(prediction))

[1 0 1 2 1 0 0 1 0 1 0 2 1 1 0 1 0 1 0 2 1 2 0 2 0 2 2 1 0 2 1 1 2 0 2 2 1
 2 1 1 0 0 2 2 2]
[1 0 1 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 1 1
 1 1 1 0 0 1 1 1]


In [ ]:
array1=ytest
array2=prediction
fig = px.line(title="Line Graph TestData vs prediction")
fig.add_scatter(x=[i for i in range(len(array1))], y=array1, mode="lines", line=dict(color="blue"), showlegend=True, name="TestData")
fig.add_scatter(x=[i for i in range(len(array2))], y=array2, mode="lines", line=dict(color="red"), showlegend=True, name="Prediction")
fig.show()

In [ ]:
dt=tree.DecisionTreeClassifier()
dt.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
prediction=dt.predict(xtest)
accuracy=accuracy_score(ytest,prediction)*100

In [ ]:
accuracy

95.55555555555556

In [ ]:
print(ytest)
print(np.array(prediction))

[1 0 1 2 1 0 0 1 0 1 0 2 1 1 0 1 0 1 0 2 1 2 0 2 0 2 2 1 0 2 1 1 2 0 2 2 1
 2 1 1 0 0 2 2 2]
[1 0 1 2 1 0 0 1 0 1 0 2 1 1 0 1 0 1 0 2 1 2 0 2 0 2 2 1 0 2 1 1 2 0 2 1 1
 2 1 1 0 0 2 1 2]


In [ ]:
array1=ytest
array2=prediction
fig = px.line(title="Line Graph TestData vs prediction")
fig.add_scatter(x=[i for i in range(len(array1))], y=array1, mode="lines", line=dict(color="blue"), showlegend=True, name="TestData")
fig.add_scatter(x=[i for i in range(len(array2))], y=array2, mode="lines", line=dict(color="red"), showlegend=True, name="Prediction")
fig.show()